
version: 2

models:
  - name: base
    description: "First Model"
    columns:
      - name: NAME
        tests:
          - unique
          - not_null

  - name: staging
    description: "Second model"
    columns:
      - name: NAME
        tests:
          - unique
          - not_null
          
  - name: final
    description: "Third Model"
    columns:
      - name: NAME
        tests:
          - unique
          - not_null